<?php

declare(strict_types=1);

// Generated by config\development\ViewDetector - do not edit by hand.
// Regenerate whenever a view file is added, removed or renamed.
// Keys are lower cased: view matching is case insensitive, and folding
// once here is cheaper than folding the map on every request.

return [
    // namespaced and unique - what BaseController::renderView() asks for first
    'views' => [
        'application/login/mail/password-reset' => __ROOT__ . '/application/login/views/mail/password-reset.php',
        'application/login/mail/password-reset-text' => __ROOT__ . '/application/login/views/mail/password-reset-text.php',
        'application/login/mail/signup-confirm' => __ROOT__ . '/application/login/views/mail/signup-confirm.php',
        'application/login/mail/signup-confirm-text' => __ROOT__ . '/application/login/views/mail/signup-confirm-text.php',
        'application/login/mail/signup-in-use' => __ROOT__ . '/application/login/views/mail/signup-in-use.php',
        'application/login/mail/signup-in-use-text' => __ROOT__ . '/application/login/views/mail/signup-in-use-text.php',
        'application/login/password/done' => __ROOT__ . '/application/login/views/password/done.php',
        'application/login/password/expired' => __ROOT__ . '/application/login/views/password/expired.php',
        'application/login/password/forgot' => __ROOT__ . '/application/login/views/password/forgot.php',
        'application/login/password/reset' => __ROOT__ . '/application/login/views/password/reset.php',
        'application/login/password/sent' => __ROOT__ . '/application/login/views/password/sent.php',
        'application/login/session/forbidden' => __ROOT__ . '/application/login/views/session/forbidden.php',
        'application/login/session/login' => __ROOT__ . '/application/login/views/session/login.php',
        'application/login/signup/check-email' => __ROOT__ . '/application/login/views/signup/check-email.php',
        'application/login/signup/confirmed' => __ROOT__ . '/application/login/views/signup/confirmed.php',
        'application/login/signup/expired' => __ROOT__ . '/application/login/views/signup/expired.php',
        'application/login/signup/index' => __ROOT__ . '/application/login/views/signup/index.php',
        'application/partials/footer' => __ROOT__ . '/application/views/partials/footer.php',
        'application/partials/header' => __ROOT__ . '/application/views/partials/header.php',
        'application/partials/nav' => __ROOT__ . '/application/views/partials/nav.php',
        'application/welcome/dashboard/index' => __ROOT__ . '/application/welcome/views/dashboard/index.php',
        'application/welcome/main/index' => __ROOT__ . '/application/welcome/views/main/index.php',
    ],
    // un-namespaced - a package ships its views here and an application
    // module overrides one just by holding the same key
    'view fallbacks' => [
        'dashboard/index' => __ROOT__ . '/application/welcome/views/dashboard/index.php',
        'debugbar/debugbar' => __ROOT__ . '/vendor/aplus/debug/src/Views/debugbar/debugbar.php',
        'errors/ajax/401' => __ROOT__ . '/vendor/orange/framework/src/views/errors/ajax/401.php',
        'errors/ajax/403' => __ROOT__ . '/vendor/orange/framework/src/views/errors/ajax/403.php',
        'errors/ajax/404' => __ROOT__ . '/vendor/orange/framework/src/views/errors/ajax/404.php',
        'errors/ajax/500' => __ROOT__ . '/vendor/orange/framework/src/views/errors/ajax/500.php',
        'errors/cli/500' => __ROOT__ . '/vendor/orange/framework/src/views/errors/cli/500.php',
        'errors/html/401' => __ROOT__ . '/vendor/orange/framework/src/views/errors/html/401.php',
        'errors/html/403' => __ROOT__ . '/vendor/orange/framework/src/views/errors/html/403.php',
        'errors/html/404' => __ROOT__ . '/vendor/orange/framework/src/views/errors/html/404.php',
        'errors/html/500' => __ROOT__ . '/vendor/orange/framework/src/views/errors/html/500.php',
        'exceptions/development' => __ROOT__ . '/vendor/aplus/debug/src/Views/exceptions/development.php',
        'exceptions/production' => __ROOT__ . '/vendor/aplus/debug/src/Views/exceptions/production.php',
        'mail/password-reset' => __ROOT__ . '/application/login/views/mail/password-reset.php',
        'mail/password-reset-text' => __ROOT__ . '/application/login/views/mail/password-reset-text.php',
        'mail/signup-confirm' => __ROOT__ . '/application/login/views/mail/signup-confirm.php',
        'mail/signup-confirm-text' => __ROOT__ . '/application/login/views/mail/signup-confirm-text.php',
        'mail/signup-in-use' => __ROOT__ . '/application/login/views/mail/signup-in-use.php',
        'mail/signup-in-use-text' => __ROOT__ . '/application/login/views/mail/signup-in-use-text.php',
        'main/index' => __ROOT__ . '/application/welcome/views/main/index.php',
        'partials/footer' => __ROOT__ . '/application/views/partials/footer.php',
        'partials/header' => __ROOT__ . '/application/views/partials/header.php',
        'partials/nav' => __ROOT__ . '/application/views/partials/nav.php',
        'password/done' => __ROOT__ . '/application/login/views/password/done.php',
        'password/expired' => __ROOT__ . '/application/login/views/password/expired.php',
        'password/forgot' => __ROOT__ . '/application/login/views/password/forgot.php',
        'password/reset' => __ROOT__ . '/application/login/views/password/reset.php',
        'password/sent' => __ROOT__ . '/application/login/views/password/sent.php',
        'session/forbidden' => __ROOT__ . '/application/login/views/session/forbidden.php',
        'session/login' => __ROOT__ . '/application/login/views/session/login.php',
        'signup/check-email' => __ROOT__ . '/application/login/views/signup/check-email.php',
        'signup/confirmed' => __ROOT__ . '/application/login/views/signup/confirmed.php',
        'signup/expired' => __ROOT__ . '/application/login/views/signup/expired.php',
        'signup/index' => __ROOT__ . '/application/login/views/signup/index.php',
    ],
    // name -> name, applied before either map is consulted
    'view aliases' => [
    ],
];
