<?php

declare(strict_types=1);

// Generated by config\development\ViewDetector - do not edit by hand.
// Regenerate whenever a view file is added, removed or renamed.
// Keys are lower cased: view matching is case insensitive, and folding
// once here is cheaper than folding the map on every request.

return [
    // namespaced and unique - what BaseController::renderView() asks for first
    'views' => [
        'application/welcome/main/index' => __ROOT__ . '/application/welcome/views/main/index.php',
        'application/welcome/partials/footer' => __ROOT__ . '/application/welcome/views/partials/footer.php',
        'application/welcome/partials/header' => __ROOT__ . '/application/welcome/views/partials/header.php',
        'application/welcome/partials/nav' => __ROOT__ . '/application/welcome/views/partials/nav.php',
    ],
    // un-namespaced - a package ships its views here and an application
    // module overrides one just by holding the same key
    'view fallbacks' => [
        'debugbar/debugbar' => __ROOT__ . '/vendor/aplus/debug/src/views/debugbar/debugbar.php',
        'errors/ajax/401' => __ROOT__ . '/vendor/orange/framework/src/views/errors/ajax/401.php',
        'errors/ajax/403' => __ROOT__ . '/vendor/orange/framework/src/views/errors/ajax/403.php',
        'errors/ajax/404' => __ROOT__ . '/vendor/orange/framework/src/views/errors/ajax/404.php',
        'errors/ajax/500' => __ROOT__ . '/vendor/orange/framework/src/views/errors/ajax/500.php',
        'errors/cli/500' => __ROOT__ . '/vendor/orange/framework/src/views/errors/cli/500.php',
        'errors/html/401' => __ROOT__ . '/vendor/orange/framework/src/views/errors/html/401.php',
        'errors/html/403' => __ROOT__ . '/vendor/orange/framework/src/views/errors/html/403.php',
        'errors/html/404' => __ROOT__ . '/vendor/orange/framework/src/views/errors/html/404.php',
        'errors/html/500' => __ROOT__ . '/vendor/orange/framework/src/views/errors/html/500.php',
        'exceptions/development' => __ROOT__ . '/vendor/aplus/debug/src/views/exceptions/development.php',
        'exceptions/production' => __ROOT__ . '/vendor/aplus/debug/src/views/exceptions/production.php',
        'main/index' => __ROOT__ . '/application/welcome/views/main/index.php',
        'partials/footer' => __ROOT__ . '/application/welcome/views/partials/footer.php',
        'partials/header' => __ROOT__ . '/application/welcome/views/partials/header.php',
        'partials/nav' => __ROOT__ . '/application/welcome/views/partials/nav.php',
    ],
    // name -> name, applied before either map is consulted
    'view aliases' => [
    ],
];
